apiVersion: apps/v1
kind: Deployment
metadata:
  name: goal-db-deployment
  labels:
    app: goal-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goal-db
  template:
    metadata:
      labels:
        app: goal-db
    spec:
      containers:
      - name: goal-db
        image: mongo
        ports:
        - containerPort: 27017
