apiVersion: v1
kind: Service
metadata:
  name: goal-web-service
spec:
  selector:
    app: goal-web
  ports:
    - name: tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer 
