apiVersion: apps/v1
kind: Deployment
metadata:
  name: goal-db-admin-deployment
  labels:
    app: goal-db-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goal-db-admin
  template:
    metadata:
      labels:
        app: goal-db-admin
    spec:
      containers:
      - name: goal-db-admin
        image: mongo-express
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
         - name: ME_CONFIG_MONGODB_SERVER
           value: goal-db-service
