apiVersion: v1
kind: Service
metadata:
  name: goal-db-admin-service
spec:
  selector:
    app: goal-db-admin
  ports:
    - name: tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer 
